saltstack-formulas/nginx-formula

nginx/ng/files/nginx.conf

this is needed on archlinux where the pid file is set by systemd
not the nginx.conf file.
In the pillar file you just add
pid:
an value of 'None' and no pid entry in nginx.conf.
this now works with every None value set in the pillar file

added test for value None, to be an absent value

---

nginx/templates/config.jinja

nginx refuse to set daemon option twice. Systemd nginx unit file set it to `no`. Thus, setting it twice breaks systemd integration.

Fix nginx config on systemd

---

nginx/ng/install.sls

This PR will enable nginx-formula to install newest version of nginx from official repo on RedHat family distributions.

Add nginx repo for RedHat family

---

nginx/ng/certificates.sls
nginx/ng/init.sls
pillar.example

I keep having to write my own states to manage nginx vhost certificates and keys. It seems like the sort of thing that should be built in to nginx-formula.
This implements it as a separate state, as simply as I could come up with. It occurred to me after writing this that it would be nice if it could detect ssl settings in a server definition and look for a matching cert/key in pillar automatically, but that could get complicated.

Added nginx.ng.certificates state.

---

nginx/ng/install.sls
nginx/ng/map.jinja
pillar.example

On Amazon Linux on EC2 - $releasever variable is set to 'latest' resulting in incorrect nginx repo url. As per http://wiki.nginx.org/Install#Official_Red_Hat.2FCentOS_packages $releasever needs to be set manually as per OS version.
Created a pillar variable nginx:ng:lookup:rh_os_releasever for the above. Default value for the pillar variable is '$releasever'

Fix for incorrect pkg repo base url on Amazon Linux on EC2

---

nginx/map.jinja
nginx/ng/map.jinja
nginx/source.sls

Updated source.sls for building in RedHat, CentOS and probably Fedora. The needed packages are selected by map.jinja based on grain=os_family in order to support Ubuntu/Debian or RedHat/CentOS/Fedora. 
While in Debian based systems we install build-essential package for all development tools, in RedHat based we can use the group 'Development Tools'. Saltstack development versions provides [pkg.group_installed](http://docs.saltstack.com/en/develop/ref/states/all/salt.states.pkg.html#salt.states.pkg.group_installed) state but as it's not available in stable versions yet I had to do a fallback to [pkg.group_install](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.yumpkg.html#salt.modules.yumpkg.group_install) module if salt version is older than ` 2015.8.0`. 
I've tested it …

Add support for building from source with os_family=RedHat

---

nginx/common.sls

To resolve the occurrence of the below error, a dependency has been added to require the nginx user first be created, either by nginx package installation or explicitly with salt (when installing nginx from source).
```
----------
ID: /var/www
Function: file.directory
Result: False
Comment: User nginx is not available Group nginx is not available
Started: 15:50:02.070799
Duration: 0.531 ms
Changes:
----------
```
I first encountered the error while using the [puppetlabs/centos-7.0-64-nocm](https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.0-64-nocm/versions/1.0.2) Vagrant box and attempting to provision nginx-formula with salt. At the time, the pillar only included the following:
```
nginx: 
use_upstart: False
```

Resolve missing dependency for nginx home dir.

---

pillar.example

This `include` appears in the default Nginx config file and I think it should also be in the pillar example as most of the setups place the active vhosts in there.

Adding default include for 'sites-enabled' dir

---

nginx/ng/files/nginx.conf

This is crap but configuration for http scope cannot be both ordered and
merged from map.jinja it seems, see issue #40.

Workaround for include being defined too early

---

nginx/package.sls

This was erroring always on Ubuntu 14.04, this fixes it.

Fix the command that was killing nginx process.

---

nginx/ng/install.sls
nginx/ng/map.jinja
pillar.example

Added option to set gpgcheck and gpgkey via pillar on rhel/centos/suse.
Related to ticket #107

Added support to control gpgcheck and gpgkey via pillar

---

nginx/ng/install.sls

On Ubuntu, you can take advantage of Personal Package Archives on Launchpad simply by specifying the user and archive name.  On other apt-based systems this must be the complete entry as it would be seen in the sources.list file.

Fix ppa install for Debian

---

nginx/ng/config.sls
nginx/ng/files/nginx.service
nginx/ng/init.sls
nginx/ng/install.sls
nginx/ng/map.jinja
nginx/ng/pkg.sls
nginx/ng/service.sls
nginx/ng/src.sls
pillar.example

Build NGINX from source with nginx.ng state with support for passing
compile time flags necessary for installing modules such as more headers
by the openresty project.

Build from source with nginx.ng

---

nginx/ng/init.sls
nginx/ng/servers.sls
nginx/ng/service.sls

the nginx ng formula refreshed the nginx service before all files are in place,
so use listen instead of watch, this will trigger the refresh only at the end of the run.

change watch to listen so it will only trigger a refresh of the service at the end

---

nginx/package.sls

A requisite should be used so that we are only issuing a kill when there is an available pid to pull from. This will allow us to avoid these types of failures:
```
ID: nginx-old-init
Function: module.wait
Name: cmd.run
Result: True
Comment: Module function cmd.run executed
Started: 21:47:27.460102
Duration: 5.6 ms
Changes:   
----------
ret:
cat: /var/run/nginx.pid: No such file or directory
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
```
With this commit the state proceeds cleanly.
```
ID: nginx-old-init
Function: module.wait
Name: cmd.run
Result: True
Comment: onlyif execution failed
Started: 21:49:15.761865
Duration: 39.185 ms
Changes:   
```

nginx/package: add onlyif requisite to nginx-old-init

---

nginx/ng/pkg.sls

It would be better to install from the os repository instead of hard coding to trusty

Use oscodename instead of hard coded trusty for deb

---

nginx/ng/pkg.sls

Hey all,
When installing from the official repository on Debian Jessie I got the following error:
```
local:
Data failed to compile:
----------
Cannot extend ID 'nginx' in 'base:nginx.ng.pkg'. It is not part of the high state.
This is likely due to a missing include statement or an incorrectly typed ID.
Ensure that a state with an ID of 'nginx' is available
in environment 'base' and to SLS 'nginx.ng.pkg'
```
This is the package name I had in the pillar:
```
local:
----------
nginx:ng:lookup:package:
nginx-full
```
I found out that the `pkg` state was looking for the fixed name *nginx* when using the official Debian repository instead of the *nginx_install* name as it was done for the Ubuntu repository. This PR fixes this problem.

Fixed reference to pkg state when installing from official Debian repo

---

nginx/ng/files/nginx.conf

With this change it is possible to add
```yaml
nginx:
ng:
server:
config:
include: /etc/nginx/modules-enabled/*.conf
```
to the pillar, which fixes the problem from #151. Without this change this would result in
```
nginx: [emerg] "load_module" directive is specified too late
```

Move includes to the top of nginx.conf

---

README.rst
nginx/ng/map.jinja
nginx/ng/passenger.sls
nginx/ng/pkg.sls
pillar.example

This PR adds a state to install Phusion passenger module from its repository.
Organized the `nginx.ng.pkg.sls` file so, when a repo is enabled the other two are disabled to avoid conflicting versions and packages.

Add support to install phusion passenger in the `ng`

---

nginx/ng/pkg.sls

Fixes #159 
Tested on debian/jessie64, centos/6, centos/7, ubuntu/xenial (16.04)

Fix missing defaults when no `install_from_*` is set

---

nginx/ng/pkg.sls

PR to workaround salt bug: https://github.com/saltstack/salt/issues/39953
- nginx failed to start on opensuse LEAP as Salt 2016.3.4 configured wrong username because following logic returned false for nginx.ng.pkg state-
`-{% if salt['grains.get']('os_family') == 'Suse' %}`
Verified solution.
`{% if salt['grains.get']('os_family') == 'Suse' or salt['grains.get']('os') == 'SUSE' %}`

Fix for OpenSuse leap, salt 2016.3.4-84.13

---

pillar.example

This PR updates the pillar.example file with my learnings from setting the pillars on three distributions, OpenSUSE (salt 2016.3), Ubuntu 17 (salt 2017.7.7), Fedora (salt 2016.11), using pillar.example as the starting point.  
The updated pillar.example removes issues below and newly commented stanzas points to fact the defaults in map.jinja are better.  IMHO, this is better pillar.example - but see also #132 
> nginx.ng.config 
> [ERROR] Rendering exception occurred: Jinja error: Undefined is not JSON serializable
>                       {{ sls_block(nginx.server.opts) }}
>                         ....
>                            config: {{ nginx.server.config|json() }}  <============
> 
> [ERROR] Rendering SLS base:nginx.ng.service failed. Jinja variable 'None' has no attribute …

Updated pillar.example file with distro learnings

---

nginx/ng/config.sls
nginx/ng/servers_config.sls
pillar.example

Enable the uploading of the different config files (nginx.conf and sites) instead of templating just adding ``source`` word in the config section (check pillar.example). In some cases can be interesting to have this possibility.
Tested in Ubuntu 14/16 and CentOS 6/7.

New feature - Enable the uploading of the config files

---

README.rst

Just got bit by missing `nginx.ng.install` as well. Went ahead and added missing docs from #118.

update README, closes #121

---

nginx/source.sls

As recommended in http://wiki.nginx.org/Debugging#Core_dump

Allow debug symbols to be included when compiling from source

---

nginx/ng/certificates.sls

Ensure that pillar.get on nginx:ng:dhparam has a sane default value if dhparam isn't defined in the pillar.

Add default value when calling pillar.get on nginx:ng:dhparam

---

nginx/ng/servers_config.sls
pillar.example

Fix for #172
What this PR does is to allow users to have this pillar data:
```yaml
nginx:
ng:
servers:
managed:
http_options.conf:
enabled: True
available_dir: /usr/local/etc/nginx
enabled_dir: /usr/local/etc/nginx
config:
- sendfile: 'on'
- tcp_nopush: 'on'
- tcp_nodelay: 'on'
- send_iowait: 12000
```
To generate a file called **/usr/local/etc/nginx/http_options.conf** with the content:
```
sendfile on;
tcp_nopush on;
tcp_nodelay on;
send_iowait 12000;
```
Without this patch a symlink is created in **/usr/local/etc/nginx/sites-enabled/http_options.conf** and **this is not desired**.

Fix for PR #172

---

nginx/ng/files/nginx.conf
pillar.example

This is similar to https://github.com/saltstack-formulas/nginx-formula/pull/157 but allows to directly specify `load_module` inside `nginx.conf` without loading external files

Allow to use load_module directly

---

pillar.example

tabs cause salt to trigger a render error because tabs are 'illegal':
```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
in "<unicode string>", line 33, column 32:
pid: /var/run/nginx.pid\t\t### Directory location must exist
^
```

Replace tabs in pillar.example with spaces.

---

nginx/ng/pkg.sls
pillar.example

Hello,
It could be useful to be able to install multiple packages such as *Nginx* modules.
If the user wants to setup virtualhosts which are using directives provided by a module, the package installation as to be performed before the restart of the service to prevent errors.
Thanks.

Allow installation of multiple packages

---

nginx/ng/map.jinja
nginx/ng/servers_config.sls

This PR does the following:
- Servers config should require available/enabled dirs to avoid race-conditions (Creating a config file without this PR failed because parent dir didn't exist).
- NGiNX service should depend on servers config.
- Servers config should create parent directories (For not common paths).
Thanks!

 Servers config should require available/enabled dirs

---

nginx/ng/servers_config.sls

This PR fixes bug that happens if `available_dir` does not exist.
```
ID: server_conf_0
Function: file.managed
Name: /etc/nginx/sites-available/default
Result: False
Comment: Parent directory not present
Started: 15:46:29.381363
Duration: 33.871 ms
Changes:   
```

makedirs needed for 'available_dir' pillar

---

nginx/ng/servers_config.sls
pillar.example

This PR fixes bugs related to managed server files being saved to wrong directory (`conf.d`)
There is no pillar named 'available' in this formula.
```
{{ server_path(server, nginx.servers.managed.get(server).get('available')) }}
```
Updated the Pillar example to clarify this. 
```
{{ server_path(server, nginx.servers.managed.get(server).get('available_dir')) }}
```
Resolves #188

Fix sites-available bug in formula logic

---

pillar.example

This PR fully resolves #96.  
The `pid_file` is already documented for `nginx.ng` but missing for `nginx` pillar example [Fixed]
There was also some incorrect indention for `nginx` pillar.example [Fixed]

Document pid_file pillar for nginx state (#96)

---

pillar.example

This PR documents tricky nginx configuration discussed in #193.
The pillar.example is based on [this example](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/#example ) and renders config shown.  Sorry for the ugly yaml.
```
stream {
server {
listen 1000;
proxy_pass lb-1000;
}
server  {
listen 53 udp;
proxy_pass dns_servers;
}
server   {
listen 12346;
proxy_pass backend4.example.com:12346;
}
upstream dns_servers {
server 192.168.136.130:53 ;
server 192.168.136.131:53 ;
server 192.168.136.132:53 ;
}
upstream lb-1000 {
server hostname1.example.com:1000;
server hostname2.example.com:1000;
}
upstream stream_backend {
least_conn ;
server backend1.example.com:12345 weight=5;
server backend2.example.com:12345 max_fails=2 fail_timeout=30s ;
server …
```

Fully document #193 stream module

---

nginx/ng/files/server.conf
pillar.example

With this one can now also write
```
- include:
- file1
- file2
```
rather than only
```
- include: file1
- include: file2
```
Both would be rendered the same.

Fix multiple values for the same key (include/listen) in server config file

---

nginx/common.sls
nginx/ng/passenger.sls
nginx/source.sls
nginx/sysvinit.sls
nginx/upstart.sls

When indentation in `context` is wrong, it can lead to errors, see https://github.com/daks/saltbug-formula for an example.

fix: corrected indentation on context in file.managed states

---

pillar.example

Just found a few issues in `pillar.example` as I was going through it adapting it to my own needs.

Pillar fixes

---

pillar.example

Continuing changes discussed in #217.
The main issue that needs discussing/testing is whether the `access_log` line (141 after this first commit) still needs to be part of `log_format` as a workaround (see #122) rather than just using the following line to specify it in YAML format.

Updating log_format in pillar.example

---

nginx/common.sls
nginx/deprecated.sls
nginx/init.sls
nginx/luajit2.sls
nginx/ng/certificates.sls
nginx/ng/config.sls
nginx/ng/init.sls
nginx/ng/passenger.sls
nginx/ng/pkg.sls
nginx/ng/servers.sls
nginx/ng/servers_config.sls
nginx/ng/service.sls
nginx/ng/snippets.sls
nginx/ng/src.sls
nginx/openresty.sls
nginx/package.sls
nginx/source.sls
nginx/sysvinit.sls
nginx/upstart.sls
nginx/users.sls

* Route all to `nginx/deprecated.sls`
---
Cross-references:
* #232 -- states deprecated.
* #233 -- main discussion about the need for this PR (after the merge).
* #235 -- warning banner added to `README`.
---
Note: There is one common state before and after: `nginx/init.sls`.  For that, I've checked for the presence of `nginx:ng` in the map instead.
Note: Implementation based on [this PR](https://github.com/saltstack-formulas/template-formula/pull/91).

fix: prevent running of states deprecated in `v1.0.0`

---

nginx/snippets.sls
pillar.example
test/salt/default/pillar/nginx.sls

Since introduction of TOFS in this formula,  we can retrieve file that are not described by pillar. TOFS  will generate source like the following:
```
nginx_snippet_letsencrypt:
source:
- salt://nginx/files/snippets/letsencrypt
- salt://nginx/files/snippets/server.conf
- salt://nginx/files/A/B/C/letsencrypt
- salt://nginx/files/A/B/C/server.conf
- salt://nginx/files/FreeBSD/letsencrypt
- salt://nginx/files/FreeBSD/server.conf
- salt://nginx/files/default/letsencrypt
- salt://nginx/files/default/server.conf
```
However, we have not same behavior between snippets file and `server_config`s.
Actually formula, append `.conf` as an extension for all snippets.
If we include `snippets/*.conf` in the main nginx.conf for example, it is not always the case that we desire to include all snippets. …

fix(snippet-file-name): removed appending of ".conf" for snippets files

---

pillar.example

This is a suggested one-liner update to docs to clarify how tofs paths work in this formula

tofs: include path pattern with defaults in docs

---

docs/TOFS_pattern.rst
nginx/libtofs.jinja

* Automated using `ssf-formula` (v0.1.0-rc.2)

chore: use `semantic-release` cross-formula standard structure

---

nginx/map.jinja

No `osfinger` grain on Archlinux (and maybe few other OS)

feat(linux): archlinux support (no osfinger grain)

---

nginx/passenger.sls

As it stands, including `nginx.passenger` doesn't do enough to result in a working install, unlike `nginx`. In my usecase, we want to be able to swap between `nginx` and `nginx.passenger` and have them be interchangeable with the same behaviour, bar the additional install & config behaviour for passenger.
IMO, that could be structured in a few ways:
1. Reuse the nginx state:
Including the state `nginx` with `install_from_phusionpassenger: true` in your pillar installs passenger + does everything that the nginx state does - if you only include nginx.passenger, you only get the passenger install same as now
2. Addon:
Treat the passenger state as an addon - so in top.sls you define:
- nginx
- nginx.passenger
Buuut in that case I think order is confusing and going to cause problems.
3. …

Included snippets, servers & certs for passenger

---

nginx/servers_config.sls
nginx/snippets.sls

---
No.
pass `nginx` to `snippets` and `server_config` contexts

feat(context): pass `nginx` to snippets and server_config contexts

---

nginx/servers.sls
nginx/servers_config.sls

servers_config should run without service dependency. As documented service with config is managed in servers.sls.

fix(servers_config): remove service depedency

---

nginx/servers.sls

---
No.
When adding `upstreams` they are added in the main `nginx.conf` file. However this file is not watched to reload/restart the service, so changes to upstreams are not catched.
This PR adds a requirement and listener so the dependency is managed correctly.

fix(servers): include main config file watch in extend

---

nginx/map.jinja
nginx/pkg.sls
pillar.example

---
- use default nginx package by default
- update devel repository URL to 15.4 + enable `gpgautoimport`, as zypper will not add repositories with unknown keys by default, causing the state to fail
- fix pkgrepo.absent bug on openSUSE
```
local:
----------
ID: nginx_zypp_repo
Function: pkgrepo.absent
Name: server_http
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/state.py", line 2215, in call
*cdata["args"], **cdata["kwargs"]
File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
return self.loader.run(run_func, *args, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1203, in run
return self._last_context.run(self._run_as, _func_or_method, …
```

Make openSUSE devel repository optional
