saltstack-formulas/nginx-formula

nginx/ng/install.sls, pillar.example
This is way cleaner, also gives more options and all of the options are built by Ubuntu team
CC: @gravyboat @nmadhok
=> Moved entirely to ubuntu's ppa

nginx/ng/map.jinja
Hi,
a minor fix for RedHat.
Regards
Johan
=> RedHat uses /var/run, not /run

nginx/ng/install.sls
=> subscribe to repo only if install_from_repo variable is set to true

nginx/templates/sysvinit-logger.jinja
Closes #85. Tested in Debian and working.
I'm not that familiar with LSB headers. Please tell me if you think something is wrong.
=> add LSB header to logger sysv init script

nginx/users.sls
=> touch htpasswd file if it doesn't exist

nginx/templates/upstart.jinja
=> Fixed runlevel on nginx upstart file

nginx/ng/certificates.sls, pillar.example
Simple but useful change for us, make configurable path to save ssl certificates.
=> Make certificates path configurable.

nginx/ng/servers_config.sls, pillar.example
**New Feature** - Added ``deleted`` option to be able to remove site files
**Improvement** - Disable reload of nginx when ``enabled=False`` in every ``state.apply`` (previously the nginx was always reloaded if ``settings.config != None``; even with ``enabled=False``)
=> New Feature/Improvement - Added deleted option to be able to remove site files

nginx/ng/certificates.sls, nginx/ng/map.jinja, pillar.example
=> Add dhparam creation

nginx/ng/certificates.sls, pillar.example
... by providing a pillar string. I developed this for use in
combination with ext_pillar and file_tree to deploy letsencrypt
certificates.
=> deploy certificates directly from pillar

nginx/common.sls, nginx/map.jinja, nginx/templates/config.jinja
slightly tested on openSUSE Leap 15.0
=> Add SUSE support and 2 small fixes

pillar.example
This PR documents workaround for https://github.com/saltstack/salt/issues/12161 described by #122
=> Document #122 solution in pillar.example

nginx/ng/pkg.sls
This PR will resolve bug reported by #179
=> Enforce PPA's on Ubuntu(s) only; not Debian

nginx/ng/map.jinja
This PR fixes #182 by enabling default nginx software behaviour. http://nginx.org/en/docs/ngx_core_module.html#worker_processes
=> Fix #182 bug

pillar.example
This PR probably resolves  issue #193
=> Document issue 93 in pillar.example

test/integration/default/controls/config.rb, test/salt/default/pillar/nginx.sls
Add test for #219: https://travis-ci.org/myii/nginx-formula/builds/524996941.
=> test(inspec): add test for `log_format` #219

docs/README.rst
As discussed starting from [this comment](https://github.com/saltstack-formulas/nginx-formula/pull/233#issuecomment-491639747) in that PR's discussion.
=> docs(readme): add warning banner about `v1.0.0` breaking changes

.travis.yml, .yamllint, pillar.example, test/integration/default/inspec.yml, test/salt/default/pillar/nginx.sls
* Semi-automated using `ssf-formula` (v0.5.0)
* Fix errors shown below:
```bash
nginx-formula$ $(grep "\- yamllint" .travis.yml | sed -e "s:^\s\+-\s\(.*\):\1:")
pillar.example
5:1       warning  missing document start "---"  (document-start)
6:89      error    line too long (110 > 88 characters)  (line-length)
7:89      error    line too long (99 > 88 characters)  (line-length)
19:89     error    line too long (132 > 88 characters)  (line-length)
35:25     warning  truthy value should be one of [false, true]  (truthy)
36:89     error    line too long (106 > 88 characters)  (line-length)
40:89     error    line too long (115 > 88 characters)  (line-length)
43:16     warning  truthy value should be one of [false, true]  (truthy)
44:89     error    line too long (105 > 88 characters) …
```
=> feat(yamllint): include for this repo and apply rules throughout

nginx/certificates.sls, test/salt/default/pillar/nginx.sls
=> fix(certificates.sls): prepare `certificates_path` dir separately

nginx/map.jinja
---
No.
* Close #261
* https://nginx.org/en/docs/ngx_core_module.html#worker_connections
=> fix(map.jinja): use upstream default for `worker_connections`

.yamllint, nginx/config.sls, nginx/map.jinja, nginx/passenger.sls, nginx/pkg.sls, nginx/snippets.sls, pillar.example, test/integration/default/controls/config.rb, test/integration/default/controls/install.rb, test/integration/default/controls/service.rb, test/integration/passenger/README.md, test/integration/passenger/controls/config.rb, test/integration/passenger/controls/install.rb, test/integration/passenger/controls/service.rb, test/integration/passenger/inspec.yml, test/salt/passenger/pillar/nginx.sls
---
No.
When installing passenger, a few errors showed up:
* Repo key for RPM is invalid.
* Resources dependencies are missing, causing configuration to fail
* Fixed a few passenger issues (resources dependencies, RPM repo key).
* Added tests for passenger installation (debian, redhat families)
* Added a parameter to allow checking the configuration before deploying (`check_config_before_apply`), disabled by default, for backward compatibility.
Added a pillar `test/salt/passenger/pillar/nginx.sls` and tests
=> Check nginx config before deploying & various passenger fixes

nginx/servers_config.sls
As per conversation in
https://github.com/saltstack-formulas/nginx-formula/commit/5d7fc8d5ba4828654c41e9f13f128260f8cf2869#commitcomment-48867113
=> fix(servers_config): fixup 05994e1

.github/workflows/kitchen.vagrant.yml, .pre-commit-config.yaml, .travis.yml, Gemfile, Gemfile.lock, kitchen.vagrant.yml, kitchen.yml, nginx/map.jinja, test/integration/default/controls/config.rb
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/308
=> ci: enable FreeBSD Vagrant-based testing using GitHub Actions

kitchen.yml, nginx/config.sls, nginx/servers_config.sls, nginx/service.sls, pillar.example, test/integration/default/controls/config.rb, test/integration/default/controls/file.rb, test/salt/default/pillar/nginx.sls, test/salt/default/states/test_dep/create_dependency_file.sls, test/salt/passenger/pillar/nginx.sls
Also, check config before applying
---
No.
This let's you add dependencies on other resources being applied for a particular vhost
A common case is when you use this formula together with letsencrypt's, validating
through nginx: you need nginx running (to validate the vhost) but can't have the ssl
vhost up until the certificate is validated (because it won't exist and will
make nginx fail to load the configuration)
=> feat(servers_config): add require statement to manage dependencies

nginx/service.sls
---
No.
The `onlyif` conditional was specified as in _ruby_ (`only_if`) and so was not being evaluated. Fixed it.
=> fix(servers): wrong conditional specification

nginx/certificates.sls, nginx/servers_config.sls, nginx/snippets.sls
nginx.servers_config wants a lightened copy of the nginx map
to render as json; but, when it was trying to remove the
servers and snippets keys from the map it assumed their presence,
causing a KeyError if they were not present by its use of .pop().
While wrapping these in an "if" clause would likely be more
correct, along with replacing .pop() with del (if jinja even
supports that) the simplest change here is to just specify a
default value for .pop(), which obviates the KeyError.
Fixes #274
---
No.
=> Ignore missing servers or snippets when removing from map

test/salt/passenger/pillar/nginx.sls
to complete on #275
---
No.
#275,  #274
This PR adds tests to changes introduced in #275
=> test(snippets): add tests for snippets' includes

nginx/snippets.sls
---
No.
`snippets` need to be deployed before building the configuration or else nginx will fail to build the configuration correctly.
This PR adds a couple of `require_in`s to ensure order.
=> fix(snippets): make sure they're deployed before being used

.pre-commit-config.yaml
=> chore: update pre-commit
